- hosts: localhost
  remote_user: root
  become: true

  tasks:
    - name: install logstash using remote .deb
      apt:
        deb: https://artifacts.elastic.co/downloads/logstash/logstash-7.6.2.deb
  
    - name: logstash - config
      copy:
        src=./files/logstash.conf
        dest=/etc/logstash/conf.d/syslog.conf
        owner=root group=root mode="u=rw,g=r,o=r"