- hosts: localhost
  remote_user: root
  become: true

  tasks:  

    - name: install basic packages
      package: name={{ item }} state=latest update_cache=yes
      become: true
      with_items:
          - docker.io
          - awscli
          - unzip
  
    - name: install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
      mode: 0755

    - name: get awscli V2
      get_url: 
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/ubuntu/awscliv2.zip

    - name: install awscli V2 
      command: unzip /home/ubuntu/awscliv2.zip && sudo /hom/ubuntu/aws/install

         