- hosts: localhost
  remote_user: root
  become: true

  #handlers:
  #  - name: restart prometheus
  #    service: name=prometheus state=restarted

  #tasks:
  #  - name: setting hostname
  #    hostname:
  #      name: "gamebot"

  #  - name: configure prometheus
  #    template:
  #      src:  /opt/ictf/logger/provisioning/prometheus.yml.j2
  #      dest: /etc/prometheus/prometheus.yml
  #    notify:
  #      restart prometheus

  tasks:
    - name: install grafana key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        id:  0D224E82057BCEE1321424B1CA6D481DBD044C76

    - name: install grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main

    - name: install packages
      package:
        name:
        - grafana
        - prometheus

    #  - name: configure prometheus
    #    template:
    #     src:  prometheus.yml.j2
    #     dest: /etc/prometheus/prometheus.yml

    - name: install elasticsearch using remote .deb
      apt:
        deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb

    - name: elasticsearch - config file
      copy:
        src=./files/elasticsearch.yml
        dest=/etc/elasticsearch/
        owner=root group=root mode="u=rw,g=r,o=r"

    - name: install kibana using remote .deb
      apt:
        deb: https://artifacts.elastic.co/downloads/kibana/kibana-7.6.2-amd64.deb

    - name: kibana - config file
      copy:
        src=./files/kibana.yml
        dest=/etc/kibana/
        owner=root group=root mode="u=rw,g=r,o=r"