---
# - name: update app armor to allow tcpdump to write in /ictf/data folder
#   file:
#     src=/etc/apparmor.d/usr.sbin.tcpdump
#     dest=/etc/apparmor.d/disable/usr.sbin.tcpdump
#     owner=root group=root mode="u=rw,g=r,o=r" state=link
#   notify:
#     - restart apparmor

# - name: copy kernel settings to server
#   template:
#     src:   templates/sysctl.conf.j2
#     dest:  /etc/sysctl.conf
#     owner: root
#     group: root
#     mode:  0644

# - name: Create config file for xt_recent so hitcount can be 255 in /etc/modeprobe.d
#   copy:
#     content: "options xt_recent ip_pkt_list_tot=255"
#     dest: /etc/modprobe.d/ip_pkt_list_tot.conf
#     force: no
#     group: root
#     owner: root
#     mode:  0644
#   register: xt_recent

# - include_role:
#     name: register_service_daemon
#   vars:
#     service_name: ictf-tcpdump
#     description: "Daemon dumping iCTF traffic"
#     command: "/usr/bin/python ictf-tcpdump.py"
#     working_directory: "/opt/ictf/router"

# - include_role:
#     name: register_service_daemon
#   vars:
#     service_name: ictf-pcap-s3
#     description: "Daemon transferring iCTF pcap backups to S3"
#     command: "/usr/bin/python ictf-pcap-s3.py"
#     working_directory: "/opt/ictf/router"

# - name: copys a script that outputs a log of packets
#   copy:
#     src="{{ICTF_FRAMEWORK_DIR_HOST}}/router/iptables_log_parse.py"
#     dest="/opt/ictf/router/iptables_log_parse.py"
#     owner=root group=root mode="u=rwx,g=rx,o=rx"


# - name: add GM specific aliases
#   copy:
#     content: "dns-resolution: no
#               promiscuous: yes
#               use-bytes: yes
#               line-display: one-line-both
#               net-filter: 172.31.129.0/19"
#     dest:  ~/.iftoprc

# - include_role:
#     name: common_server
#   vars:
#     server_hostname: router

# - include_role:
#     name: deploy_prometheus_node_exporter

- name: add openvpn key
  apt_key:
    id:  30EBF4E73CCE63EEE124DD278E6DA8B4E158C569
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: add openvpn repo
  apt_repository:
    repo: deb http://build.openvpn.net/debian/openvpn/release/2.4 xenial main
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'

- name: install openvpn
  apt:
    name:  openvpn
    state: latest

- name: create openvpn log directory
  file:
    path:  /var/log/openvpn
    state: directory
    owner: root
    group: root
    mode:  0755
