---
- name: install iptables-persistent
  package:
    name:  iptables-persistent
    state: latest

- name: configure iptables
  template:
    src:      templates/rules.v4.j2
    dest:     /etc/iptables/rules.v4
  notify:
  - reload iptables

- name: allow packet forwarding
  template:
    src:  templates/sysctl.conf.j2
    dest: /etc/sysctl.conf
  notify:
  - reload sysconfig
