- hosts: localhost
  remote_user: root
  become: true

  vars:
    - AWS_REGISTRY_URL: "{{ AWS_REGISTRY_URL | regex_replace('/.*', '') }}"
    - USER_HOME_DIRECTORY: /home/ubuntu
    - USER: ubuntu

  tasks:  
    - name: setting hostname
      hostname:
        name: "database"
    
    - name: create .aws directory
      file:
        path: "{{ USER_HOME_DIRECTORY }}/.aws"
        state: directory
      become_user: "{{ USER }}"

    - name: setting permission for deploy script
      template: 
        src: ./files/aws_credentials.j2
        dest: "{{ USER_HOME_DIRECTORY }}/.aws/credentials"
      become_user: "{{ USER }}"

    - name: Fix permission for deploy script
      file: 
        path: "{{ USER_HOME_DIRECTORY }}/ares_provisioning/deploy_on_ec2.sh"
        mode: a+x

    - name: login to docker and pull private image
      command: "{{ USER_HOME_DIRECTORY }}/ares_provisioning/deploy_on_ec2.sh {{ AWS_REGION }} {{ AWS_REGISTRY_URL }}"
      become_user: "{{ USER }}"
    
    - name: copy docker-compose in home
      copy:
        src: "{{ USER_HOME_DIRECTORY }}/ares_provisioning/docker-compose.yml"
        dest: "{{ USER_HOME_DIRECTORY }}/docker-compose.yml"
      become_user: "{{ USER }}"

    - name: start container
      shell: docker-compose up -d
      args:
        chdir: "{{ USER_HOME_DIRECTORY }}"
      become_user: "{{ USER }}"
      

    # - name: create aws_router_config.yml
    #   template:
    #     src: ./files/aws_config.yml.j2
    #     dest: /opt/ictf/database/aws_config.yml

    # - name: Fix permission for configuration file
    #   file:
    #     path: /opt/ictf/database/aws_config.yml
    #     owner: hacker
    #     group: hacker
    #     mode: 0755
      # notify:
      #   - restart ictf-db-export-s3
