ICTF_DB_API_SECRET: "{{ lookup('password','/opt/ictf/secrets/api_secret length=25') }}"
ICTF_DB_API_ADDRESS: "{{ lookup('password','/opt/ictf/secrets/api_address length=25') }}"
ICTF_TI_SERVER_URL: "https://api.ictf2017.net"
ICTF_TI_SECRET_KEY: "{{ lookup('password','/opt/ictf/secrets/ti_secret length=25') }}"

SENDGRID_API_KEY: "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"
ICTF_EMAIL_SENDER: "noreply@ictf2017.net"
ICTF_TI_SERVER_DOMAIN: "api.ictf2017.net"

# to obtain a SSL cert with letsencrypt see https://certbot.eff.org/#ubuntutrusty-nginx
SSL_CERTIFICATE_PATH: "/etc/letsencrypt/live/api.ictf2017.net/fullchain.pem"
SSL_CERTIFICATE_KEY_PATH: "/etc/letsencrypt/live/api.ictf2017.net/privkey.pem"
ENABLE_SSL: "0"

# Team interface config
REGISTRATION_OPEN: "True"
GAME_STARTED: "False"
SUBMISSION_OPEN: "False"
