---
- name: install grafana key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    id:  0D224E82057BCEE1321424B1CA6D481DBD044C76

- name: install grafana repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: install packages
  package:
    name:
    - grafana
    - prometheus

# - name: configure prometheus
#   template:
#     src:  prometheus.yml.j2
#     dest: /etc/prometheus/prometheus.yml

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: run grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true

- include_role:
    name: common_server
  vars:
    server_hostname: Logger

- name: install requirements
  package: name={{ item }} state=latest update_cache=yes
  become: true
  with_items:
    - nginx
    - uwsgi
    - uwsgi-plugin-python
    - mysql-server
    - python-pip
    - python-virtualenv
    - python-mysqldb
    - python-dev
    - awscli
    - openjdk-8-jdk 
    - openjdk-8-jdk-headless
    - openjdk-8-jre
  tags: [skip_ansible_lint]

- name: Upgrade pip and setuptools and related modules for cryptography fixes
  pip:
    name:
      - pip
      - setuptools
      - pyOpenSSL
      - ndg-httpsclient
      - pyasn1
    state: latest
    extra_args: --upgrade
  become: true

- name: install elasticsearch using remote .deb
  apt:
    deb: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb

- name: elasticsearch - config file
  copy:
    src=elasticsearch.yml
    dest=/etc/elasticsearch/
    owner=root group=root mode="u=rw,g=r,o=r"

- name: install kibana using remote .deb
  apt:
    deb: https://artifacts.elastic.co/downloads/kibana/kibana-7.6.2-amd64.deb

- name: kibana - config file
  copy:
    src=kibana.yml
    dest=/etc/kibana/
    owner=root group=root mode="u=rw,g=r,o=r"